<?php

namespace Requestum\ApiBundle\Action;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SubResourceDecorator implements ActionInterface
{
    private $baseAction;

    private $options = [
        'fetch_field' => 'user',
        'request_attr' => 'id'
    ];

    /**
     * SubResourceDecorator constructor.
     *
     * @param EntityAction $action
     */
    public function __construct(EntityAction $action)
    {
        $this->baseAction = $action;
    }

    /**
     * @inheritdoc
     */
    public function executeAction(Request $request)
    {
        $requestAttr = $request->attributes->get($this->options['request_attr']);

        if($this->options['fetch_field'] == null || $requestAttr === null) {
            new NotFoundHttpException();
        }

        $filterExtension = new SubResourseFilter($this->options['fetch_field'], $requestAttr);
        $this->baseAction->addFiltersExtension($filterExtension);

        return $this->baseAction->executeAction($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param $options
     */
    public function configureOptions($options)
    {
        $resolver = new OptionsResolver();

        $resolver->setDefaults($this->options);

        $this->options = $resolver->resolve($options);
    }
}
