# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_UNCOMPLETED_PROFILE
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        auth_user_provider:
            id: auth.security.user_provider
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api/
            fos_oauth:  true
            stateless:  true

        main:
            anonymous: ~

    access_decision_manager:
        allow_if_all_abstain: true
        strategy: affirmative

    access_control:
        - { path: ^/api/users, method: POST, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/me, roles: [ROLE_USER, ROLE_UNCOMPLETED_PROFILE] }
        - { path: ^/api/users/.*/forgot-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/.*/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users.*, method: PATCH, role: ROLE_UNCOMPLETED_PROFILE }
        - { path: ^/api, role: ROLE_USER }
