imports:
  - { resource: actions/* }
  - { resource: voters/* }

services:
    user_listener:
        class: AppBundle\EventListener\UserListener
        arguments:
            - '@security.user_password_encoder.generic'
        tags:
            - { name: doctrine.orm.entity_listener }

    user_subscriber:
        class: AppBundle\Subscriber\UserSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@core.util.error_factory'
            - '@validator'

        tags:
            - { name: kernel.event_subscriber }

    app.upload_listener:
        class: AppBundle\EventListener\UploadListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    app.service.reset_password:
        class: AppBundle\Service\ResetPassword\ResetPassword
        arguments: ["@doctrine.orm.entity_manager", "@requestum_email_sender", "%default_email_from%", "%reset_password_link_template%"]
